HEO01 - Number of Graduates in Ireland - 2010 - 2019

https://data.cso.ie/table/HEO01

Notes: The number of graduates refers only to `young’ graduates and includes those graduation records with missing or invalid PPSN.
For more information, please refer to the chapters Background Statistics and Background Notes on the.

Higher Education Outcomes - Graduation Years 2010-2019

## <font color='#1ABC9C'>MSC_DA_CA1<font color='#00A859'>
#### <font color='#'>**Programming for DA - Statistics for Data Analytics - Machine Learning for Data Analysis & Data Preparation & Visualisation
#### <font color='#1D76BA'>**Lecturer(s): Sam Weiss/ David Gonzalez, Bharathi Chakravarthi/ Marina Iantorno, Muhammad Iqbal and David McQuaid**
------
<font color='#E74C3C'>**Students name / ID** // Rosilene Francisca da Silva 2021090

*This is a project using PYTHON programming language to use data to Analysis the Scenario of Population in Ireland.*</font>

## Exploratory Data Analysis (EDA)

In [1]:
# Importing the required libraries:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
# Importing the Dataset 
popcensus_df = pd.read_csv('population_each_census.csv')

In [10]:
popcensus_df.head(10)

             Statistic Label  CensusYear   County         Sex    UNIT    VALUE
0  Population at Each Census        1841    State  Both sexes  Number  6528799
1  Population at Each Census        1841    State        Male  Number  3222485
2  Population at Each Census        1841    State      Female  Number  3306314
3  Population at Each Census        1841   Carlow  Both sexes  Number    86228
4  Population at Each Census        1841   Carlow        Male  Number    42428
5  Population at Each Census        1841   Carlow      Female  Number    43800
6  Population at Each Census        1841   Dublin  Both sexes  Number   372773
7  Population at Each Census        1841   Dublin        Male  Number   170930
8  Population at Each Census        1841   Dublin      Female  Number   201843
9  Population at Each Census        1841  Kildare  Both sexes  Number   114488

In [4]:
popcensus_df.shape

(2106, 6)

In [5]:
popcensus_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2106 entries, 0 to 2105
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Statistic Label  2106 non-null   object
 1   CensusYear       2106 non-null   int64
 2   County           2106 non-null   object
 3   Sex              2106 non-null   object
 4   UNIT             2106 non-null   object
 5   VALUE            2106 non-null   int64
dtypes: int64(2), object(4)
memory usage: 98.8+ KB

#### The dataset has in total 9,240 rows each having 7 features.

In [6]:
popcensus_df.dtypes

Statistic Label    object
CensusYear          int64
County             object
Sex                object
UNIT               object
VALUE               int64
dtype: object

In [7]:
# Getting summary statistics
popcensus_df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
CensusYear,2106.0,1946.576923,53.843841,1841.0,1901.0,1958.5,1991.00,2022.0
VALUE,2106.0,184978.583096,514012.411834,12013.0,36617.0,63490.5,111867.25,6528799.0

In [8]:
popcensus_df.describe()

        CensusYear         VALUE
count  2106.000000  2.106000e+03
mean   1946.576923  1.849786e+05
std      53.843841  5.140124e+05
min    1841.000000  1.201300e+04
25%    1901.000000  3.661700e+04
50%    1958.500000  6.349050e+04
75%    1991.000000  1.118672e+05
max    2022.000000  6.528799e+06

In [11]:
popcensus_df.isnull().values.any()

False

In [12]:
popcensus_df.isnull().sum()

Statistic Label    0
CensusYear         0
County             0
Sex                0
UNIT               0
VALUE              0
dtype: int64

In [13]:
popcensus_df.isnull()

      Statistic Label  CensusYear  County    Sex   UNIT  VALUE
0               False       False   False  False  False  False
1               False       False   False  False  False  False
2               False       False   False  False  False  False
3               False       False   False  False  False  False
4               False       False   False  False  False  False
...               ...         ...     ...    ...    ...    ...
2101            False       False   False  False  False  False
2102            False       False   False  False  False  False
2103            False       False   False  False  False  False
2104            False       False   False  False  False  False
2105            False       False   False  False  False  False

[2106 rows x 6 columns]

In [15]:
#check for any duplicates 
duplicate = popcensus_df[popcensus_df.duplicated(keep='first')]
print(duplicate)

Empty DataFrame
Columns: [Statistic Label, CensusYear, County, Sex, UNIT, VALUE]
Index: []

In [16]:
Value = popcensus_df['CensusYear']
Value

0       1841
1       1841
2       1841
3       1841
4       1841
        ...
2101    2022
2102    2022
2103    2022
2104    2022
2105    2022
Name: CensusYear, Length: 2106, dtype: int64

In [18]:
popcensus_df.nunique()

Statistic Label       1
CensusYear           26
County               27
Sex                   3
UNIT                  1
VALUE              2095
dtype: int64

## Data Understanding & Preprocessing

###### Clearly, the string data present in the dataframe is structured as an object, necessitating a conversion back to its string format for further processing.

In [19]:
string_col = popcensus_df.select_dtypes(include="object").columns
popcensus_df[string_col]=popcensus_df[string_col].astype("string")

In [20]:
popcensus_df.dtypes

Statistic Label    string
CensusYear          int64
County             string
Sex                string
UNIT               string
VALUE               int64
dtype: object

#### Converting data types
Now, as we can see here the object data has been converted to string

In [ ]:
# to convert the features to numeric types (integers)
datagrad_df['NField of Study'] = pd.to_numeric(datagrad_df['Field of Study'])
datagrad_df['NFQ Level'] = pd.to_numeric(datagrad_df['NFQ Level'])
datagrad_df['Nationality'] = pd.to_numeric(datagrad_df['Nationality'])

# Verify the conversion
print(datagrad_df.dtypes)

In [ ]:
# Creating a sample DataFrame
datagrad_df = {'NFQ Level: All NFQ Levels, NFQ Level 10': ['1', '2', '3', '4']}
df = pd.DataFrame(datagrad_df)

# Converting the column to integers
df['NFQ Leve: All NFQ Levels, NFQ Level 10'] = df['NFQ Level: All NFQ Levels, NFQ Level 10'].astype(int)

# Printing the DataFrame
print(df)

In [ ]:
#Renaming some columns with the 'rename' methods because it's more appropriate.
datagrad_df = datagrad_df.rename(columns={'Graduation Year': 'GradYear','NFQ Level': 'NFQLevel', 'VALUE': 'Value'})
datagrad_df.head(2)

In [ ]:
value_nationality = datagrad_df.groupby('Nationality')[['Value']].sum()
print(value_nationality.sort_values(by = ['Value']))

In [ ]:
plt.figure(figsize=(10,5))
popcensus_df['CensusYear'].value_counts().plot.bar()
plt.xticks(rotation=70)
plt.bar(xpos,salary, label='Salary')

In [ ]:
plt.figure(figsize=(10,5))
sns.barplot(x='NFQLevel',y='Value',data=datagrad_df,hue='GradYear')
plt.xticks(rotation=70)
##Checking the distribution of Capital_gain and  Occupation as per gender##

In [ ]:
count = (popcensus_df['CensusYear'] == ('State').sum()
count

In [ ]:
sns.set(style="darkgrid")
plt.figure(figsize=(16, 6))

sns.countplot(data=datagrad_df, x='Nationality', order=datagrad_df['Nationality'].value_counts().head(20).index)
plt.xticks(rotation=45)  #for better readability
plt.title('Count of Nationality')
plt.xlabel('Nationality')
plt.ylabel('Count')

plt.show()

In [ ]:
sns.violinplot(x= 'GradYear', y='Value', data=datagrad_df)

In [ ]:
#WE can use .T, right after sample(5) to transpose the Feature and this method will work in cascade and sequentially.
#datapop_df.head(5).T

In [ ]:
#If we wannt to change the colors
#We need to add the labels!
colors = ['red', 'yellow', 'violet']
fig, ax = plt.subplots()
ax.bar(value_nfqlevel.index, value_nfqlevel['Value'], color = colors, edgecolor = 'red')

plt.xlabel('NFQLevel')
plt.ylabel('Value')
plt.title('NFQLevel Number')